### ISSUE TITLE
Update README to describe how someone becomes a member of `/wlcg/test` group in IAM

### ISSUE THREAD

**Issue by paulmillar** [indigo-iam/wlcg-jwt-compliance-tests#22]
The "wlcg/test group grants full access to /protected area" test requires that the user is able to obtain a token with `wlcg.groups` claim containing `/wlcg/test` group.  In other words, that the user is a member of the `/wlcg/test` group in the WLCG IAM instance.

People are not a member by default, and must somehow join this group.

This requirement and how to satisfy it should be documented in the README file somewhere.

**Comment by federicaagostini** [comment]
PR #31
