### ISSUE TITLE
Include short summary of test results in email

### ISSUE THREAD

**Issue by bbockelm** [indigo-iam/wlcg-jwt-compliance-tests#26]
To be honest, I read the email to decide on whether I want to click on the link... we should have some indication of test results in the email itself to entice folks to look at further details.  It's a surprisingly large mental "hurdle" to get out of the email client!

**Comment by federicaagostini** [comment]
PR #30

**Comment by giacomini** [comment]
I have merged the PR so that tomorrow we have a report with a summary and we can get some feedback. I leave the issue open for the moment
