### ISSUE TITLE
Make protected path configurable

### ISSUE THREAD

**Issue by paulmillar** [indigo-iam/wlcg-jwt-compliance-tests#6]
The conformance tests check that only requests using a valid AuthZ token is able to read/write into a protected directory.

Such a directory already exists in the prometheus endpoint, but it isn't called `protected`, but `Private` (i.e., `/VOs/wlcg/Private`).

Could we make the protected path configurable so that the prometheus endpoint could be configured to use `/VOs/wlcg/Private` ?

**Comment by andreaceccanti** [comment]
Hi Paul, as discussed in chat, no problem in having this configurable per endpoint (with the default being /protected).

**Comment by paulmillar** [comment]
Actually, I've decided this doesn't make any sense -- at least, for me.  Let's just keep it simple: people have to set up their storage correctly, which includes having a `/protected` directory as described.
